**Assignment Chapter 1 - Foundation for Data Science**

**Python Foundation**

Anggota Kelompok :     
- SC60602 - Andri Maulana
- SC60605 - Hana Maheswari
- SC60615 - Kevin Jesse Haryanto
- SC60617 - Nurul Inayah
- SC60625 - Uut Permatasari

# <b>Soal 1</b>

Kumpulkan data dari seluruh anggota kompi, jika kamu berasal dari kompi A, maka buatlah dataframe df_a, jika kamu berasal dari kompi B, maka buat df_b, dst. Lalu, kumpulkan seluruh data dari seluruh peserta, yang meliputi No. Peserta, Nama, Jurusan, Berat Badan (kg), Tinggi Badan (cm). Dengan dataset yang sudah terkumpul, jawab beberapa pertanyaan berikut:

## <b>No 1</b>

Identifikasi dan jelaskan tipe data apa saja yang ada pada dataframe, ada berapa kolom dan baris, serta informasi apa saja yang terkandung dalam data tersebut?

In [ ]:
import pandas as pd
import urllib.request

url = 'https://docs.google.com/spreadsheets/d/1tP5z1H-7NS4R62_ZFKmbkTbjiFrULencaSSrNGuVYPM/export?format=csv&id=1tP5z1H-7NS4R62_ZFKmbkTbjiFrULencaSSrNGuVYPM'
filename = 'data.csv'

urllib.request.urlretrieve(url, filename)
df_6 = pd.read_csv(filename, encoding='utf-8')

# Tampilkan data
display(df_6)

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm)
0,SC60601,Ade Ayu Eka Setiasih,Sastra Jawa,44,155
1,SC60602,Andri Maulana,Manajemen,52,161
2,SC60603,Dea Siti Rosita,Ilmu Administrasi Negara,51,155
3,SC60604,Erlina Eka Mayasari,Matematika,45,157
4,SC60605,Hana Maheswari,Teknik Informatika,64,169
5,SC60606,Lilis Anggraini,Rekayasa Sistem Komputer,45,155
6,SC60607,Muhamad Aditia Fahmi,Sistem Informasi,45,165
7,SC60608,Nabila Amina Rashydny,Pendidikan Fisika,56,155
8,SC60609,Nurul Zahra,Teknik Informatika,75,160
9,SC60610,Rizki Ramdani,Teknik Informatika,70,173
10,SC60611,Syifa Mufidah,Teknik Industri,55,167
11,SC60612,Al Farrah Az-Zahra,Matematika,60,156
12,SC60613,Bryan Rizqi Prakosa,Teknik Informatika,70,170
13,SC60614,Fathia Rahmaisty,Matematika,50,157
14,SC60615,Kevin Jesse Haryanto,Ekonomi Pembangunan,55,172
15,SC60616,Muhammad Farras Rabbani,Manajemen,63,173
16,SC60617,Nurul Inayah,Teknik Informatika,59,155
17,SC60618,Satria Imawan,Sistem Informasi,50,170
18,SC60619,Agnes Monica Puspitaningtyas,Statistika,43,155
19,SC60620,Aristo Lie,Bisnis Digital,85,170
20,SC60621,Eggy B. Brillian,Sistem Informasi,70,173
21,SC60622,Intan Sari Nur Ekmah,Statistika,52,160
22,SC60623,Nadia Adyutarahma Putri,Matematika,47,151
23,SC60624,Rahmad Kholid,Statistika,55,169
24,SC60625,Uut Permatasari,Akuntansi,43,160

Tabel di atas adalah semua data yang ada pada dataframe.

In [ ]:
# Menampilkan informasi pada data
df_6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   No. Peserta        25 non-null     object
 1   Nama               25 non-null     object
 2   Jurusan            25 non-null     object
 3   Berat Badan (kg)   25 non-null     int64
 4   Tinggi Badan (cm)  25 non-null     int64
dtypes: int64(2), object(3)
memory usage: 1.1+ KB

Tipe data yang ada pada dataframe tersebut adalah object dan integer.

- Tipe data "object" menunjukkan bahwa kolom tersebut berisi data objek Python yang umumnya berupa string, tetapi dapat juga berisi tipe data lain seperti list atau tipe data campuran.

- Tipe data "integer" menunjukkan bahwa kolom tersebut berisi bilangan bulat. Bilangan bulat digunakan karena berat badan dan tinggi badan umumnya diukur dalam satuan bilangan bulat, seperti kilogram dan sentimeter.

In [ ]:
# Mendapatkan nama kolom
print(df_6.columns)

# Hitung jumlah baris dan kolom
jumlah_baris, jumlah_kolom = df_6.shape

# Tampilkan hasil
print(f"Jumlah baris: {jumlah_baris}")
print(f"Jumlah kolom: {jumlah_kolom}")

Index(['No. Peserta', 'Nama', 'Jurusan', 'Berat Badan (kg)',
       'Tinggi Badan (cm)'],
      dtype='object')
Jumlah baris: 25
Jumlah kolom: 5

Dataframe tersebut memiliki 25 baris dan 5 kolom.

Dan berisi informasi No. Peserta, Nama, Jurusan, Berat Badan (kg), dan Tinggi Badan (cm).

## <b>No 2, 3, 4</b>

Hitunglah BMI setiap siswa dengan rumus BMI = Berat badan (kg)/(Tinggi Badan (m))^2

Buatlah program untuk menghitung BMI!

Update dataframe df dengan menambahkan hasil perhitungan soal nomor 2, beri nama kolom BMI.

In [ ]:
# Hitung BMI untuk setiap siswa dan menambahkan kolom baru 'BMI'
df_6['BMI'] = df_6['Berat Badan (kg)'] / ((df_6['Tinggi Badan (cm)'] / 100) ** 2)

# Tampilkan data
display(df_6)

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI
0,SC60601,Ade Ayu Eka Setiasih,Sastra Jawa,44,155,18.314256
1,SC60602,Andri Maulana,Manajemen,52,161,20.060954
2,SC60603,Dea Siti Rosita,Ilmu Administrasi Negara,51,155,21.227888
3,SC60604,Erlina Eka Mayasari,Matematika,45,157,18.256319
4,SC60605,Hana Maheswari,Teknik Informatika,64,169,22.408179
5,SC60606,Lilis Anggraini,Rekayasa Sistem Komputer,45,155,18.730489
6,SC60607,Muhamad Aditia Fahmi,Sistem Informasi,45,165,16.528926
7,SC60608,Nabila Amina Rashydny,Pendidikan Fisika,56,155,23.309053
8,SC60609,Nurul Zahra,Teknik Informatika,75,160,29.296875
9,SC60610,Rizki Ramdani,Teknik Informatika,70,173,23.388687
10,SC60611,Syifa Mufidah,Teknik Industri,55,167,19.721037
11,SC60612,Al Farrah Az-Zahra,Matematika,60,156,24.654832
12,SC60613,Bryan Rizqi Prakosa,Teknik Informatika,70,170,24.221453
13,SC60614,Fathia Rahmaisty,Matematika,50,157,20.284799
14,SC60615,Kevin Jesse Haryanto,Ekonomi Pembangunan,55,172,18.591130
15,SC60616,Muhammad Farras Rabbani,Manajemen,63,173,21.049818
16,SC60617,Nurul Inayah,Teknik Informatika,59,155,24.557752
17,SC60618,Satria Imawan,Sistem Informasi,50,170,17.301038
18,SC60619,Agnes Monica Puspitaningtyas,Statistika,43,155,17.898023
19,SC60620,Aristo Lie,Bisnis Digital,85,170,29.411765
20,SC60621,Eggy B. Brillian,Sistem Informasi,70,173,23.388687
21,SC60622,Intan Sari Nur Ekmah,Statistika,52,160,20.312500
22,SC60623,Nadia Adyutarahma Putri,Matematika,47,151,20.613131
23,SC60624,Rahmad Kholid,Statistika,55,169,19.257029
24,SC60625,Uut Permatasari,Akuntansi,43,160,16.796875

Tabel di atas adalah semua data yang ada pada dataframe, setelah ditambahkan kolom BMI dari hasil perhitungan.

## <b>No 5</b>

Buatlah status BMI untuk setiap siswa dari kategori berikut, lalu simpan data statusnya dengan nama kolom Status BMI.
- Normal: 18.5-24.9
- Overweight: 25.0-29.9
- Obesity: 30.0-34.9
- Underweight: < 18.5

In [ ]:
# Membuat fungsi kategori BMI
def kategori_bmi(bmi):
  if 18.5 <= bmi < 24.9:
      return "Normal"
  elif 25.0 <= bmi < 29.9:
      return "Overweight"
  elif 30.0 <= bmi < 34.9:
      return "Obesity"
  elif bmi < 18.5:
    return "Underweight"
  else :
    # lebih dari 34.9
    return "Very Obesity"

# Tambahkan kolom dengan kategori BMI
df_6['Status BMI'] = df_6['BMI'].apply(kategori_bmi)

# Tampilkan data
display(df_6)

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
0,SC60601,Ade Ayu Eka Setiasih,Sastra Jawa,44,155,18.314256,Underweight
1,SC60602,Andri Maulana,Manajemen,52,161,20.060954,Normal
2,SC60603,Dea Siti Rosita,Ilmu Administrasi Negara,51,155,21.227888,Normal
3,SC60604,Erlina Eka Mayasari,Matematika,45,157,18.256319,Underweight
4,SC60605,Hana Maheswari,Teknik Informatika,64,169,22.408179,Normal
5,SC60606,Lilis Anggraini,Rekayasa Sistem Komputer,45,155,18.730489,Normal
6,SC60607,Muhamad Aditia Fahmi,Sistem Informasi,45,165,16.528926,Underweight
7,SC60608,Nabila Amina Rashydny,Pendidikan Fisika,56,155,23.309053,Normal
8,SC60609,Nurul Zahra,Teknik Informatika,75,160,29.296875,Overweight
9,SC60610,Rizki Ramdani,Teknik Informatika,70,173,23.388687,Normal
10,SC60611,Syifa Mufidah,Teknik Industri,55,167,19.721037,Normal
11,SC60612,Al Farrah Az-Zahra,Matematika,60,156,24.654832,Normal
12,SC60613,Bryan Rizqi Prakosa,Teknik Informatika,70,170,24.221453,Normal
13,SC60614,Fathia Rahmaisty,Matematika,50,157,20.284799,Normal
14,SC60615,Kevin Jesse Haryanto,Ekonomi Pembangunan,55,172,18.591130,Normal
15,SC60616,Muhammad Farras Rabbani,Manajemen,63,173,21.049818,Normal
16,SC60617,Nurul Inayah,Teknik Informatika,59,155,24.557752,Normal
17,SC60618,Satria Imawan,Sistem Informasi,50,170,17.301038,Underweight
18,SC60619,Agnes Monica Puspitaningtyas,Statistika,43,155,17.898023,Underweight
19,SC60620,Aristo Lie,Bisnis Digital,85,170,29.411765,Overweight
20,SC60621,Eggy B. Brillian,Sistem Informasi,70,173,23.388687,Normal
21,SC60622,Intan Sari Nur Ekmah,Statistika,52,160,20.312500,Normal
22,SC60623,Nadia Adyutarahma Putri,Matematika,47,151,20.613131,Normal
23,SC60624,Rahmad Kholid,Statistika,55,169,19.257029,Normal
24,SC60625,Uut Permatasari,Akuntansi,43,160,16.796875,Underweight

Tabel di atas adalah semua data yang ada pada dataframe, setelah ditambahkan kolom Status BMI dari pengkategorian pada fungsi.

## <b>No 6</b>

a. Buatlah variabel baru lalu urutkan data berdasarkan tinggi badan dari yang tertinggi ke rendah.

b. Buat variabel baru lalu urutkan data berdasarkan Nama dari Z – A.

In [ ]:
# Membuat variabel baru dan diurutkan berdasarkan tinggi badan
df_6_urutan_tinggi = df_6.sort_values(by='Tinggi Badan (cm)', ascending=False)

# Tampilkan data
display(df_6_urutan_tinggi)

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
20,SC60621,Eggy B. Brillian,Sistem Informasi,70,173,23.388687,Normal
9,SC60610,Rizki Ramdani,Teknik Informatika,70,173,23.388687,Normal
15,SC60616,Muhammad Farras Rabbani,Manajemen,63,173,21.049818,Normal
14,SC60615,Kevin Jesse Haryanto,Ekonomi Pembangunan,55,172,18.591130,Normal
12,SC60613,Bryan Rizqi Prakosa,Teknik Informatika,70,170,24.221453,Normal
19,SC60620,Aristo Lie,Bisnis Digital,85,170,29.411765,Overweight
17,SC60618,Satria Imawan,Sistem Informasi,50,170,17.301038,Underweight
23,SC60624,Rahmad Kholid,Statistika,55,169,19.257029,Normal
4,SC60605,Hana Maheswari,Teknik Informatika,64,169,22.408179,Normal
10,SC60611,Syifa Mufidah,Teknik Industri,55,167,19.721037,Normal
6,SC60607,Muhamad Aditia Fahmi,Sistem Informasi,45,165,16.528926,Underweight
1,SC60602,Andri Maulana,Manajemen,52,161,20.060954,Normal
21,SC60622,Intan Sari Nur Ekmah,Statistika,52,160,20.312500,Normal
24,SC60625,Uut Permatasari,Akuntansi,43,160,16.796875,Underweight
8,SC60609,Nurul Zahra,Teknik Informatika,75,160,29.296875,Overweight
13,SC60614,Fathia Rahmaisty,Matematika,50,157,20.284799,Normal
3,SC60604,Erlina Eka Mayasari,Matematika,45,157,18.256319,Underweight
11,SC60612,Al Farrah Az-Zahra,Matematika,60,156,24.654832,Normal
16,SC60617,Nurul Inayah,Teknik Informatika,59,155,24.557752,Normal
18,SC60619,Agnes Monica Puspitaningtyas,Statistika,43,155,17.898023,Underweight
7,SC60608,Nabila Amina Rashydny,Pendidikan Fisika,56,155,23.309053,Normal
5,SC60606,Lilis Anggraini,Rekayasa Sistem Komputer,45,155,18.730489,Normal
2,SC60603,Dea Siti Rosita,Ilmu Administrasi Negara,51,155,21.227888,Normal
0,SC60601,Ade Ayu Eka Setiasih,Sastra Jawa,44,155,18.314256,Underweight
22,SC60623,Nadia Adyutarahma Putri,Matematika,47,151,20.613131,Normal

Tabel di atas adalah semua data yang ada pada dataframe, setelah diurutkan berdasarkan tinggi badan dari tinggi ke rendah.

In [ ]:
# Membuat variabel baru dan diurutkan berdasarkan nama dari Z-A
df_6_urutan_nama = df_6.sort_values(by='Nama', ascending = False)

# Tampilkan data
display(df_6_urutan_nama)

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
24,SC60625,Uut Permatasari,Akuntansi,43,160,16.796875,Underweight
10,SC60611,Syifa Mufidah,Teknik Industri,55,167,19.721037,Normal
17,SC60618,Satria Imawan,Sistem Informasi,50,170,17.301038,Underweight
9,SC60610,Rizki Ramdani,Teknik Informatika,70,173,23.388687,Normal
23,SC60624,Rahmad Kholid,Statistika,55,169,19.257029,Normal
8,SC60609,Nurul Zahra,Teknik Informatika,75,160,29.296875,Overweight
16,SC60617,Nurul Inayah,Teknik Informatika,59,155,24.557752,Normal
22,SC60623,Nadia Adyutarahma Putri,Matematika,47,151,20.613131,Normal
7,SC60608,Nabila Amina Rashydny,Pendidikan Fisika,56,155,23.309053,Normal
15,SC60616,Muhammad Farras Rabbani,Manajemen,63,173,21.049818,Normal
6,SC60607,Muhamad Aditia Fahmi,Sistem Informasi,45,165,16.528926,Underweight
5,SC60606,Lilis Anggraini,Rekayasa Sistem Komputer,45,155,18.730489,Normal
14,SC60615,Kevin Jesse Haryanto,Ekonomi Pembangunan,55,172,18.591130,Normal
21,SC60622,Intan Sari Nur Ekmah,Statistika,52,160,20.312500,Normal
4,SC60605,Hana Maheswari,Teknik Informatika,64,169,22.408179,Normal
13,SC60614,Fathia Rahmaisty,Matematika,50,157,20.284799,Normal
3,SC60604,Erlina Eka Mayasari,Matematika,45,157,18.256319,Underweight
20,SC60621,Eggy B. Brillian,Sistem Informasi,70,173,23.388687,Normal
2,SC60603,Dea Siti Rosita,Ilmu Administrasi Negara,51,155,21.227888,Normal
12,SC60613,Bryan Rizqi Prakosa,Teknik Informatika,70,170,24.221453,Normal
19,SC60620,Aristo Lie,Bisnis Digital,85,170,29.411765,Overweight
1,SC60602,Andri Maulana,Manajemen,52,161,20.060954,Normal
11,SC60612,Al Farrah Az-Zahra,Matematika,60,156,24.654832,Normal
18,SC60619,Agnes Monica Puspitaningtyas,Statistika,43,155,17.898023,Underweight
0,SC60601,Ade Ayu Eka Setiasih,Sastra Jawa,44,155,18.314256,Underweight

Tabel di atas adalah semua data yang ada pada dataframe, setelah diurutkan berdasarkan berdasarkan nama dari Z ke A.

## <b>No 7</b>

Filter dataframe df berdasarkan:

a.  Status BMI di luar Normal

In [ ]:
# Membuat variabel baru dan mencari status BMI di luar normal
df_6_status_bmi_tidak_normal = df_6[df_6['Status BMI'] != 'Normal']

# Tampilkan data
display(df_6_status_bmi_tidak_normal)

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
0,SC60601,Ade Ayu Eka Setiasih,Sastra Jawa,44,155,18.314256,Underweight
3,SC60604,Erlina Eka Mayasari,Matematika,45,157,18.256319,Underweight
6,SC60607,Muhamad Aditia Fahmi,Sistem Informasi,45,165,16.528926,Underweight
8,SC60609,Nurul Zahra,Teknik Informatika,75,160,29.296875,Overweight
17,SC60618,Satria Imawan,Sistem Informasi,50,170,17.301038,Underweight
18,SC60619,Agnes Monica Puspitaningtyas,Statistika,43,155,17.898023,Underweight
19,SC60620,Aristo Lie,Bisnis Digital,85,170,29.411765,Overweight
24,SC60625,Uut Permatasari,Akuntansi,43,160,16.796875,Underweight

b. Tinggi Badan > 169 cm dan Berat Badan > 60 kg

In [ ]:
# Membuat variabel baru dan memfilter tinggi badan dan berat badan
df_6_tinggi_dan_berat = df_6[(df_6['Tinggi Badan (cm)'] > 169) & (df_6['Berat Badan (kg)'] > 60)]

# Tampilkan data
display(df_6_tinggi_dan_berat)

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
9,SC60610,Rizki Ramdani,Teknik Informatika,70,173,23.388687,Normal
12,SC60613,Bryan Rizqi Prakosa,Teknik Informatika,70,170,24.221453,Normal
15,SC60616,Muhammad Farras Rabbani,Manajemen,63,173,21.049818,Normal
19,SC60620,Aristo Lie,Bisnis Digital,85,170,29.411765,Overweight
20,SC60621,Eggy B. Brillian,Sistem Informasi,70,173,23.388687,Normal

c. Nama yang mengandung huruf “y”

In [ ]:
# Membuat variabel baru dan memfilter nama yang mengandung huruf 'y'
df_6_nama_mengandung_y = df_6[df_6['Nama'].str.contains('y')]

# Tampilkan data
display(df_6_nama_mengandung_y)

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
0,SC60601,Ade Ayu Eka Setiasih,Sastra Jawa,44,155,18.314256,Underweight
3,SC60604,Erlina Eka Mayasari,Matematika,45,157,18.256319,Underweight
7,SC60608,Nabila Amina Rashydny,Pendidikan Fisika,56,155,23.309053,Normal
10,SC60611,Syifa Mufidah,Teknik Industri,55,167,19.721037,Normal
12,SC60613,Bryan Rizqi Prakosa,Teknik Informatika,70,170,24.221453,Normal
13,SC60614,Fathia Rahmaisty,Matematika,50,157,20.284799,Normal
14,SC60615,Kevin Jesse Haryanto,Ekonomi Pembangunan,55,172,18.591130,Normal
16,SC60617,Nurul Inayah,Teknik Informatika,59,155,24.557752,Normal
18,SC60619,Agnes Monica Puspitaningtyas,Statistika,43,155,17.898023,Underweight
20,SC60621,Eggy B. Brillian,Sistem Informasi,70,173,23.388687,Normal
22,SC60623,Nadia Adyutarahma Putri,Matematika,47,151,20.613131,Normal

d. Siapa saja yang berat badannya kurang dari 60 kg

In [ ]:
# Membuat variabel baru dan mencari berat badan kurang dari 60 kg
df_6_berat_badan = df_6[df_6['Berat Badan (kg)'] < 60]

# Tampilkan data
display(df_6_berat_badan)

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
0,SC60601,Ade Ayu Eka Setiasih,Sastra Jawa,44,155,18.314256,Underweight
1,SC60602,Andri Maulana,Manajemen,52,161,20.060954,Normal
2,SC60603,Dea Siti Rosita,Ilmu Administrasi Negara,51,155,21.227888,Normal
3,SC60604,Erlina Eka Mayasari,Matematika,45,157,18.256319,Underweight
5,SC60606,Lilis Anggraini,Rekayasa Sistem Komputer,45,155,18.730489,Normal
6,SC60607,Muhamad Aditia Fahmi,Sistem Informasi,45,165,16.528926,Underweight
7,SC60608,Nabila Amina Rashydny,Pendidikan Fisika,56,155,23.309053,Normal
10,SC60611,Syifa Mufidah,Teknik Industri,55,167,19.721037,Normal
13,SC60614,Fathia Rahmaisty,Matematika,50,157,20.284799,Normal
14,SC60615,Kevin Jesse Haryanto,Ekonomi Pembangunan,55,172,18.591130,Normal
16,SC60617,Nurul Inayah,Teknik Informatika,59,155,24.557752,Normal
17,SC60618,Satria Imawan,Sistem Informasi,50,170,17.301038,Underweight
18,SC60619,Agnes Monica Puspitaningtyas,Statistika,43,155,17.898023,Underweight
21,SC60622,Intan Sari Nur Ekmah,Statistika,52,160,20.312500,Normal
22,SC60623,Nadia Adyutarahma Putri,Matematika,47,151,20.613131,Normal
23,SC60624,Rahmad Kholid,Statistika,55,169,19.257029,Normal
24,SC60625,Uut Permatasari,Akuntansi,43,160,16.796875,Underweight

## <b>No 8</b>

Tambahkan nomor urut pada dataframe df sesuai jumlah siswa dan tempatkan kolom nomor baru tersebut di paling ujung kiri sebagai kolom pertama serta beri nama kolomnya “No.”!

In [ ]:
# Menambahkan nomor urut dan memberi nama "No"
df_6['No.'] = range(1, len(df_6) + 1)

# Kolom diletakkan di kiri
columns = ['No.'] + [col for col in df_6.columns if col != 'No.']
df_6 = df_6[columns]

# Tampilkan data
display(df_6)

,No.,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
0,1,SC60601,Ade Ayu Eka Setiasih,Sastra Jawa,44,155,18.314256,Underweight
1,2,SC60602,Andri Maulana,Manajemen,52,161,20.060954,Normal
2,3,SC60603,Dea Siti Rosita,Ilmu Administrasi Negara,51,155,21.227888,Normal
3,4,SC60604,Erlina Eka Mayasari,Matematika,45,157,18.256319,Underweight
4,5,SC60605,Hana Maheswari,Teknik Informatika,64,169,22.408179,Normal
5,6,SC60606,Lilis Anggraini,Rekayasa Sistem Komputer,45,155,18.730489,Normal
6,7,SC60607,Muhamad Aditia Fahmi,Sistem Informasi,45,165,16.528926,Underweight
7,8,SC60608,Nabila Amina Rashydny,Pendidikan Fisika,56,155,23.309053,Normal
8,9,SC60609,Nurul Zahra,Teknik Informatika,75,160,29.296875,Overweight
9,10,SC60610,Rizki Ramdani,Teknik Informatika,70,173,23.388687,Normal
10,11,SC60611,Syifa Mufidah,Teknik Industri,55,167,19.721037,Normal
11,12,SC60612,Al Farrah Az-Zahra,Matematika,60,156,24.654832,Normal
12,13,SC60613,Bryan Rizqi Prakosa,Teknik Informatika,70,170,24.221453,Normal
13,14,SC60614,Fathia Rahmaisty,Matematika,50,157,20.284799,Normal
14,15,SC60615,Kevin Jesse Haryanto,Ekonomi Pembangunan,55,172,18.591130,Normal
15,16,SC60616,Muhammad Farras Rabbani,Manajemen,63,173,21.049818,Normal
16,17,SC60617,Nurul Inayah,Teknik Informatika,59,155,24.557752,Normal
17,18,SC60618,Satria Imawan,Sistem Informasi,50,170,17.301038,Underweight
18,19,SC60619,Agnes Monica Puspitaningtyas,Statistika,43,155,17.898023,Underweight
19,20,SC60620,Aristo Lie,Bisnis Digital,85,170,29.411765,Overweight
20,21,SC60621,Eggy B. Brillian,Sistem Informasi,70,173,23.388687,Normal
21,22,SC60622,Intan Sari Nur Ekmah,Statistika,52,160,20.312500,Normal
22,23,SC60623,Nadia Adyutarahma Putri,Matematika,47,151,20.613131,Normal
23,24,SC60624,Rahmad Kholid,Statistika,55,169,19.257029,Normal
24,25,SC60625,Uut Permatasari,Akuntansi,43,160,16.796875,Underweight

Tabel di atas adalah semua data yang ada pada dataframe, setelah ditambahkan kolom nomor baru.

## <b>No 9</b>

Cari nilai-nilai berikut:

a. Cari nilai terendah dan tertingginya.

In [ ]:
# Mencari nilai terendah dan tertinggi menggunakan kolom
nilai_terendah_berat_badan = df_6['Berat Badan (kg)']. min()
nilai_tertinggi_berat_badan = df_6['Berat Badan (kg)']. max()
nilai_terendah_tinggi_badan = df_6['Tinggi Badan (cm)']. min()
nilai_tertinggi_tinggi_badan = df_6['Tinggi Badan (cm)'].max()
nilai_terendah_bmi = df_6['BMI'].min()
nilai_tertinggi_bmi = df_6['BMI'].max()

# Tampilkan data
print(f'Berat badan terendah : {nilai_terendah_berat_badan} kg')
print(f'Berat badan tertinggi : {nilai_tertinggi_berat_badan} kg')
print(f'Tinggi badan terendah : {nilai_terendah_tinggi_badan} cm')
print(f'Tinggi badan tertinggi : {nilai_tertinggi_tinggi_badan} cm')
print(f'BMI terendah : {nilai_terendah_bmi:.2f}')
print(f'BMI tertinggi : {nilai_tertinggi_bmi:.2f}')

Berat badan terendah : 43 kg
Berat badan tertinggi : 85 kg
Tinggi badan terendah : 151 cm
Tinggi badan tertinggi : 173 cm
BMI terendah : 16.53
BMI tertinggi : 29.41

b. Berapa nilai rata-rata tinggi badan siswa?

c. Berapa rata-rata berat badan siswa?

In [ ]:
# Mencari rata-rata tinggi badan dan berat badan menggunakan kolom
rata_rata_tinggi_badan = df_6['Tinggi Badan (cm)']. mean()
rata_rata_berat_badan = df_6['Berat Badan (kg)']. mean()

# Tampilkan data
print(f'Rata rata tinggi badan : {rata_rata_tinggi_badan} cm')
print(f'Rata rata berat badan : {rata_rata_berat_badan} kg')

Rata rata tinggi badan : 162.52 cm
Rata rata berat badan : 56.16 kg

c. Ada berapa orang jumlah siswa  yang tercatat pada dataframe df?

In [ ]:
# Mencari jumlah siswa yang tercatat menggunakan kolom
Jumlah_siswa = len(df_6)

# Tampilkan data
print(f'Jumlah siswa : {Jumlah_siswa} orang')

Jumlah siswa : 25 orang

d. 5 orang dengan nilai BMI tertinggi.

In [ ]:
# Mencari 5 orang dengan nilai BMI tertinggi menggunakan kolom
tertinggi_5_bmi = df_6.nlargest(5, 'BMI')

# Tampilkan data
display(tertinggi_5_bmi)

,No.,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
19,20,SC60620,Aristo Lie,Bisnis Digital,85,170,29.411765,Overweight
8,9,SC60609,Nurul Zahra,Teknik Informatika,75,160,29.296875,Overweight
11,12,SC60612,Al Farrah Az-Zahra,Matematika,60,156,24.654832,Normal
16,17,SC60617,Nurul Inayah,Teknik Informatika,59,155,24.557752,Normal
12,13,SC60613,Bryan Rizqi Prakosa,Teknik Informatika,70,170,24.221453,Normal

e. Ada berapa orang yang tergolong status Underweight, Normal, Overweight, dan Obesity?

In [ ]:
# Mencari jumlah orang yang berdasarkan status BMI menggunakan kolom
Jumlah_Underweight = len(df_6[df_6['Status BMI'] == 'Underweight'])
Jumlah_Normal = len(df_6[df_6['Status BMI'] == 'Normal'])
Jumlah_Overweight = len(df_6[df_6['Status BMI'] == 'Overweight'])
Jumlah_Obesity = len(df_6[df_6['Status BMI'] == 'Obesity'])


# Tampilkan data
print(f'Jumlah siswa Underweight : {Jumlah_Underweight} orang')
print(f'Jumlah siswa Normal : {Jumlah_Normal} orang')
print(f'Jumlah siswa Overweight : {Jumlah_Overweight} orang')
print(f'Jumlah siswa Obesity : {Jumlah_Obesity} orang')

Jumlah siswa Underweight : 6 orang
Jumlah siswa Normal : 17 orang
Jumlah siswa Overweight : 2 orang
Jumlah siswa Obesity : 0 orang

# <b>Soal 2</b>

Perusahaan Investasi Jamin-Sugih Co kami memberikan penawaran investasi terbaik dengan pembagian keuntungan tetap sebesar 25% setiap tahun.

Buatlah program Python yang dapat menerima input dari pengguna dalam bentuk:

Modal Investasi (bilangan bulat antara 0-1.000.000.000)

Jangka Waktu Investasi (bilangan bulat antara 1-25 dalam tahun)

Selain itu, program akan menampilkan error message bahwa modal atau tenure tidak sesuai ketentuan.

Program akan menampilkan informasi akumulasi investasi setiap tahun, menggunakan iterasi untuk setiap tahun.

In [ ]:
# Minta pengguna untuk memasukkan modal investasi dan jangka waktu investasi
modal = int(input("Masukkan Modal Investasi (0-1.000.000.000): "))
tenure = int(input("Masukkan Jangka Waktu Investasi (1-25 tahun): "))

# Periksa apakah modal investasi dan jangka waktu investasi berada dalam rentang yang ditentukan
if not(0 <= modal <= 1000000000) or not(1 <= tenure <= 25):
    print("Modal atau tenure tidak sesuai ketentuan.")
else:
    # Jika modal investasi dan jangka waktu investasi valid, gunakan loop untuk menghitung dan mencetak total investasi untuk setiap tahun
    for i in range(1, tenure + 1):
        modal *= 1.25
        print("Tahun {}, total investasi : {}".format(i, modal))

Masukkan Modal Investasi (0-1.000.000.000): 100000
Masukkan Jangka Waktu Investasi (1-25 tahun): 2
Tahun 1, total investasi : 125000.0
Tahun 2, total investasi : 156250.0